elasticsearch:
  image: elasticsearch:5.4
  ports:
    - "9200:9200"


    
es_web:
  build: Dockerfile_py2
  volumes:
      - ./:/es
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  links:
    - elasticsearch

